"""recommendation table

Revision ID: bb52de43f56d
Revises: c14dc2dd026e
Create Date: 2021-03-20 10:49:14.495423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb52de43f56d'
down_revision = 'c14dc2dd026e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=127), nullable=False),
    sa.Column('item_id', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('similarity_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item1_id', sa.String(length=200), nullable=False),
    sa.Column('item2_id', sa.String(length=200), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similarity_model')
    op.drop_table('rating')
    # ### end Alembic commands ###
