"""product and variant table

Revision ID: e32bb2d4f116
Revises: c35c91374eae
Create Date: 2021-03-19 09:58:24.095735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e32bb2d4f116'
down_revision = 'c35c91374eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=127), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('texture', sa.String(length=127), nullable=True),
    sa.Column('wash', sa.String(length=127), nullable=True),
    sa.Column('place', sa.String(length=127), nullable=True),
    sa.Column('note', sa.String(length=127), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('main_image', sa.String(length=255), nullable=True),
    sa.Column('images', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=127), nullable=True),
    sa.Column('image_base64', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.create_index(op.f('ix_product_title'), 'product', ['title'], unique=False)
    op.create_table('variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color_code', sa.String(length=15), nullable=True),
    sa.Column('color_name', sa.String(length=15), nullable=True),
    sa.Column('size', sa.String(length=15), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variant')
    op.drop_index(op.f('ix_product_title'), table_name='product')
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
